set (MXA_QT_SRCS
    ${MXA_SOURCE_DIR}/MXA/Qt/ApplicationAboutBoxDialog.cpp
    ${MXA_SOURCE_DIR}/MXA/Qt/QRecentFileList.cpp
    ${MXA_SOURCE_DIR}/MXA/Qt/QFileCompleter.cpp
    ${MXA_SOURCE_DIR}/MXA/Qt/MXAImageGraphicsDelegate.cpp
    ${MXA_SOURCE_DIR}/MXA/Qt/QFSDroppableGraphicsView.cpp
    ${MXA_SOURCE_DIR}/MXA/Qt/ProcessQueueDialog.cpp
    ${MXA_SOURCE_DIR}/MXA/Qt/ProcessQueueController.cpp
    ${MXA_SOURCE_DIR}/MXA/Qt/ProcessQueueTask.cpp
)
set (MXA_QT_HDRS
    ${MXA_SOURCE_DIR}/MXA/Qt/ApplicationAboutBoxDialog.h
    ${MXA_SOURCE_DIR}/MXA/Qt/QRecentFileList.h
    ${MXA_SOURCE_DIR}/MXA/Qt/QFileCompleter.h
    ${MXA_SOURCE_DIR}/MXA/Qt/MXAImageGraphicsDelegate.h
    ${MXA_SOURCE_DIR}/MXA/Qt/QFSDroppableGraphicsView.h
    ${MXA_SOURCE_DIR}/MXA/Qt/ProcessQueueDialog.h
    ${MXA_SOURCE_DIR}/MXA/Qt/ProcessQueueController.h
    ${MXA_SOURCE_DIR}/MXA/Qt/ProcessQueueTask.h
)
IDE_SOURCE_PROPERTIES("CrossCorrelation/Qt" "${MXA_QT_HDRS}" "${MXA_QT_SRCS}")


# --------------------------------------------------------------------
# The UI files As generated by Qt Designer
# --------------------------------------------------------------------
SET( MXA_QT_UI_FILES
  ${MXA_SOURCE_DIR}/MXA/Qt/UI_Files/ProcessQueueDialog.ui
  ${MXA_SOURCE_DIR}/MXA/Qt/UI_Files/ApplicationAboutBoxDialog.ui
)
